name:                aHaskellPriori
version:             2019.10.23.1
github:              "Denbergvanthijs/aHaskellPriori"
license:             Apache-2.0
author:              "Thijs van den Berg"
maintainer:          "denbergvanthijs@gmail.com"
copyright:           "2019 Thijs van den Berg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Apriori algoritm in Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Denbergvanthijs/aHaskellPriori#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- matrix

library:
  source-dirs: src

executables:
  aHaskellPriori-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aHaskellPriori

tests:
  aHaskellPriori-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aHaskellPriori
